<?php

return [
    ['code' => '+591', 'country' => 'Bolivia'],
    ['code' => '+54', 'country' => 'Argentina'],
    ['code' => '+55', 'country' => 'Brasil'],
    ['code' => '+56', 'country' => 'Chile'],
    ['code' => '+57', 'country' => 'Colombia'],
    ['code' => '+506', 'country' => 'Costa Rica'],
    ['code' => '+53', 'country' => 'Cuba'],
    ['code' => '+593', 'country' => 'Ecuador'],
    ['code' => '+503', 'country' => 'El Salvador'],
    ['code' => '+502', 'country' => 'Guatemala'],
    ['code' => '+504', 'country' => 'Honduras'],
    ['code' => '+52', 'country' => 'México'],
    ['code' => '+505', 'country' => 'Nicaragua'],
    ['code' => '+507', 'country' => 'Panamá'],
    ['code' => '+595', 'country' => 'Paraguay'],
    ['code' => '+51', 'country' => 'Perú'],
    ['code' => '+1', 'country' => 'EE.UU. / Canadá'],
    ['code' => '+598', 'country' => 'Uruguay'],
    ['code' => '+58', 'country' => 'Venezuela'],
    ['code' => '+501', 'country' => 'Belice'],
    ['code' => '+509', 'country' => 'Haití'],
    ['code' => '+1809', 'country' => 'Rep. Dominicana'],
    ['code' => '+1787', 'country' => 'Puerto Rico'],
    ['code' => '+1876', 'country' => 'Jamaica'],
    ['code' => '+1868', 'country' => 'Trinidad y Tobago'],
    ['code' => '+34', 'country' => 'España'],
    ['code' => '+351', 'country' => 'Portugal'],
    ['code' => '+49', 'country' => 'Alemania'],
    ['code' => '+33', 'country' => 'Francia'],
    ['code' => '+39', 'country' => 'Italia'],
    ['code' => '+44', 'country' => 'Reino Unido'],
    ['code' => '+31', 'country' => 'Países Bajos'],
    ['code' => '+32', 'country' => 'Bélgica'],
    ['code' => '+41', 'country' => 'Suiza'],
    ['code' => '+43', 'country' => 'Austria'],
    ['code' => '+46', 'country' => 'Suecia'],
    ['code' => '+47', 'country' => 'Noruega'],
    ['code' => '+48', 'country' => 'Polonia'],
    ['code' => '+7', 'country' => 'Rusia / Kazajistán'],
    ['code' => '+81', 'country' => 'Japón'],
    ['code' => '+82', 'country' => 'Corea del Sur'],
    ['code' => '+86', 'country' => 'China'],
    ['code' => '+91', 'country' => 'India'],
    ['code' => '+61', 'country' => 'Australia'],
    ['code' => '+64', 'country' => 'Nueva Zelanda'],
    ['code' => '+27', 'country' => 'Sudáfrica'],
    ['code' => '+20', 'country' => 'Egipto'],
    ['code' => '+971', 'country' => 'Emiratos Árabes'],
    ['code' => '+966', 'country' => 'Arabia Saudita'],
    ['code' => '+90', 'country' => 'Turquía'],
    ['code' => '+972', 'country' => 'Israel'],
];
